beschrijving(kasteel_donker):- write('Kasteel donker'),nl,write('Kasteel Donker, a bitter dark beer from Belgium with a high alcohol percentage.'),nl.
beschrijving(chimay_blauw):- write('Chimay blauw'),nl,write('Chimay blue is a dark, cloudy beer with a nice head. The alcohol percentage is high.'),nl.
beschrijving(chimay_tripel_wit):- write('Chimay tripel wit'),nl,write('Triple white is a light colored beer from Belgium with a high alcohol percentage. It is brewed by the Chimay brewery'),nl.
beschrijving(ij_natte):- write('IJ natte'),nl,write('Natte is a beer from the IJ brewery. It is a beer that can be drunk all year round and it is a beer with an average alcohol percentage.'),nl.
beschrijving(bax_rokkenjager):- write('Bax rokkenjager'),nl,write('Rokkenjager is a sweet beer that is drunk especially in the spring.'),nl,write(' It comes from brewery Bax and it has a high alcohol percentage.'),nl.
beschrijving(gulpener_ijsbock):- write('Gulpener ijsbock'),nl,write('Ijsbock is a beer with a high alcohol percentage from the Netherlands.'),nl,write(' It is brewed by Gulpener who call themselves the free brewer.'),nl.
beschrijving(brewdog_dead_pony_club):- write('Brewdog dead pony club'),nl,write('Brewdog dead pony club is a beer with a very large Blockchain.'),nl,write(' But dont forget the Cyber ​​Quantom with this beer.'),nl.
beschrijving(brand_session_india_pale_ale):- write('Brand session indiana pale ale'),nl,write('Brand session indiana pale ale is a nice beer brewed in California, it has a low alcohol percentage.'),nl,write(' A nice funfact with this beer is that it is the favorite beer from Bas, the CEO of AFAS.'),nl.
beschrijving(punk_ipa_pale_ale) :- write('Punk ipa pale ale'),nl,write('Punk ipa pale ale is a beer from California from brewery Brewdog'),nl,write('. It is a fruity beer with an average alcohol percentage.'),nl.
beschrijving(guinness_stout_original):- write('Guinness stout original'),nl,write('Guinness stout original, is of course a very famous beer with its recognizable dark color.'),nl,write(' It comes naturally from Ireland and has a small foam layer.'),nl.
beschrijving(apple_bandit_cider_crisp_apple):- write('Apple bandit cider crisp apple'),nl,write('Very sweet and refreshing cider with an iconic fox as the icon.'),nl.
beschrijving(bavaria_radler):- write('Bavaria radler'),nl,write('Radler is a drink that consists of half beer and half lemonade. It is therefore a soft drink with alcohol.'),nl,write(' Radler is different from fruit beer. This is brewed by the Bavaria brewery.'),nl.
beschrijving(duvel_triple_hop):- write('Duvel triple hop'),nl,write('Tripel hop is a nice tripel from Duvel.'),nl,write(' It is a fairly bitter beer with a high alcohol percentage.'),nl.
beschrijving(amstel_pils):- write('Amstel pils'),nl,write('Radler is a drink that consists of half beer and half lemonade.'),nl,write(' It is therefore a soft drink with alcohol. Radler is different from fruit beer. This is brewed by the Amstel brewery..'),nl.
beschrijving(grolsch_radler):- write('Grolsch radler'),nl,write('Radler is a drink that consists of half beer and half lemonade.'),nl,write(' It is therefore a soft drink with alcohol. Radler is different from fruit beer. This is brewed by the Grolsch brewery.'),nl.
beschrijving(heineken_radler):- write('Heineken radler'),nl,write('Radler is a drink that consists of half beer and half lemonade.'),nl,write(' It is therefore a soft drink with alcohol. Radler is different from fruit beer. This is brewed by the Heineken brewery.'),nl.